# Build the entire program and clean up .o files
all:
	g++ -Wall -c Superhero.cpp main.cpp Heros.cpp
	g++ *.o -o Superhero.out
	rm *.o
# Only build the Superhero class
hero:
	g++ -Wall -c Superhero.cpp -o Superhero.o
